name: Build Windows MSIX (Code Signed)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Setup Code Signing Certificate
        if: ${{ secrets.CERTIFICATE_BASE64 }}
        run: |
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 -d > cert.p12
          echo "CSC_LINK=cert.p12" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.CERTIFICATE_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Windows MSIX (Signed)
        run: npm run build-win-msix

      - name: Build Windows NSIS (Signed)
        run: npm run build-win-installer

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v3
        with:
          name: excel-splitter-msix-signed
          path: dist/*.msix

      - name: Upload NSIS artifact
        uses: actions/upload-artifact@v3
        with:
          name: excel-splitter-nsis-signed
          path: dist/*.exe

      - name: Cleanup
        if: always()
        run: |
          if (Test-Path cert.p12) { Remove-Item cert.p12 }
